datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: aloutta
    password: S3cret
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - com.github.aloutta.gaming.catalog.persistence
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
flyway:
  datasources:
    default:
      enabled: true