datasources.default.dialect: POSTGRES
flyway.datasources.default.enabled: true
jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres